# Generated by Django 6.0.6 on 2026-06-29 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["operation_type__name", "name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="operationtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Тип операции",
                "verbose_name_plural": "Типы операций",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["name"],
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": [
                    "category__operation_type__name",
                    "category__name",
                    "name",
                ],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
    ]
